### ISSUE TITLE
Satella2 requires unusable dependency on iOS 14

### ISSUE THREAD

**Issue by eoyoa** [Paisseon/Satella#4]
# Device and Tweak Information

See #3 for relevant information.

# Issue

Satella2 requires Orion (iOS 12-13), but it cannot be installed on devices of iOS 14.

# Possible fix

Orion Runtime (iOS 14) seems to work as a replacement.

**Comment by Paisseon** [comment]
I'm pretty sure this is a bug with some package managers. The dependency is dev.theos.orion, whereas Orion (12-13) is dev.theos.orion12 and Orion (iOS 14) is dev.theos.orion14. It's up to the package manager to determine which dependency is correct, and since I want to keep iOS 12-13 compatibility if possible, I can only suggest either manually installing the correct dependency or using another package manager. Saily seems to work properly.
