### ISSUE TITLE
Server side spoofing for popular libraries shared by many apps

### ISSUE THREAD

**Issue by sodiboo** [Paisseon/Satella#6]
> Correct, server sided purchases can't work. It would require adding app-specific support, which is out of Satella's scope.

Although i agree app-specific support is unreasonable, how about library-specific support? For example with revenuecat, is it possible to spoof its server response and have it work in all apps using that library? Have you thought about implementing anything like this in Satella?

__Originally posted by @Terrain2 in https://github.com/Paisseon/Satella/issues/7#issuecomment-1082343270__

**Comment by Lunascaped** [comment]
This seems like a good idea actually

**Comment by Paisseon** [comment]
I've been working on this for RevenueCat. It cracks RevenueCat's server-sided IAPs now, albeit in a very limited fashion. Probably 80-90% of apps won't work until I find a better way of searching for the expected value (logging `[NSDictionary objectForKey:]` seems too resource-intensive to be worth it) because right now, I have to hardcode the entitlement identifiers.

Basically, RevenueCat apps usually only store the identifiers inside a subscript for the `[RCEntitlementInfos all]` which means that unless there is some method of which I am unaware, it's not possible to have a fully-functional generic cracker for RevenueCat. Tbh, it might be better to just use this as a template for app-specific cracks as those could hardcode the *correct* identifiers instead of random ones.

Possible workaround is to read a .plist in which users can manually add identifiers specific to their apps, but I imagine the average user wouldn't feel like trying to reverse something and I *really* don't want to get 1000 requests to find identifiers...

Will release the update once I have either improved the reliability or given up 😉

Btw if you know of a RevenueCat app with multiple IAPs, preferably written in Objective-C and including one or more subscriptions, that would be helpful!

**Comment by Veshurik** [comment]
Where is releases? Why no releases at all?

**Comment by Paisseon** [comment]
> Where is releases? Why no releases at all?

???
It's in version 1.2, which was released over a week ago

**Comment by Veshurik** [comment]
I mean, I can't see a .deb file in "Releases" section to download. Unfortunately, I can't install it through repo, cause I have an error "APT was unable to find this package"

**Comment by Paisseon** [comment]
Ah, gotcha. The deb is here: https://github.com/Paisseon/paisseon.github.io/blob/master/debs/emt.paisseon.satella_1.2_iphoneos-arm.deb

**Comment by Veshurik** [comment]
Thanks. I installed it, but unfortunately, there's no any button in Settings to turn it on.
Command in terminal "uicache -ar" doesn't help :(

UPD. It finally worked, I just needed to install LocalAPStore to finally be able to see Satella menu.
Now I wonder where and how I should use functions "Receipts", Observer, Sideloaded Apps and RevenueCat. Thanks!

**Comment by Paisseon** [comment]
Receipts has a decent success rate on iOS 13, and a practically nonexistant one on 14
Observer fixes some things, breaks others (rarely), and usually has no effect
Sideloaded Apps is self-explanatory
Revenue Cat is for cracking apps using the RevenueCat framework, albeit with a low success rate

From what I hear, most users just keep all the toggles on and disable if something crashes :p

**Comment by Veshurik** [comment]
Oh, thanks. 
Tried on some games, of course, I think, almost all of them are server-side purchases, so...

But I found old games which works with LocalAp, but doesn't work with Satella 2, interesting!

**Comment by Paisseon** [comment]
What are the old games?

**Comment by Veshurik** [comment]
Like "Run Roo Run" by 5th Cell Game Studios (deleted now in AppStore, now here's F2P version by another company).

**Comment by Paisseon** [comment]
Are you sure it's not an older version that's vulnerable? I just tried Run Roo Run v1.2.36 with Satella 2, then Satella 2 + LocalIAPStore, then just LocalIAPStore and the purchase didn't work with any.

**Comment by Veshurik** [comment]
I'm using 0.6.6 version

**Comment by Paisseon** [comment]
The oldest I can find is 1.2.12 🤷‍♀️

**Comment by Paisseon** [comment]
Removed this from Satella and Satella Jailed, it's now in a separate tweak "RevenueCat Crack."
